---
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '50050'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.37.0
    container_name: weaviate
    ports:
      - 50060:50050
      - 50061:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'multi2vec-clip'
      CLUSTER_HOSTNAME: 'node1'
      CLIP_INFERENCE_API: http://multi2vec-clip:8080

  multi2vec-clip:
    image: cr.weaviate.io/semitechnologies/multi2vec-clip:sentence-transformers-clip-ViT-B-32
    container_name: clip
    ports:
      - 8888:8080
    environment:
      ENABLE_CUDA: '0'
    #  ENABLE_CUDA: '1'
    #deploy:
    #    resources:
    #      reservations:
    #        devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [gpu]

  # acuity:
  #   # image: codeberg.org/shlks/acuity:latest
  #   # container_name: acuity
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ".:/app"
  #     - "acuity_data:/app/data"
  #     - "gocache_vol:/app/tmp"
  #     - "/media/data/Wallpaper:/data/Wallpaper:rw"
  #     - "/home/shlks/Projects/acuity/raw:/data/raw"
  #     - "/media/misc/.arrogant-frog:/data/arrogant-frog"
  #   working_dir: /app
  #   environment:
  #     - WEAVIATE_HOST=weaviate
  #     - WEAVIATE_PORT=:50050
  #     - GOCACHE=/app/tmp/gocache
  #     - GOMODCACHE=/app/tmp/gomodcache
  #     - DEBUG=true
  #     - PORT=3000
  #   restart: on-failure

volumes:
  weaviate_data:
    name: weaviate_data_dev
  acuity_data:
   name: sqlite_data_dev
  gocache_vol:
   name: gocache_vol
