---
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '50050'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.37.0
    container_name: weaviate
    ports:
    - 50050:50050
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'multi2vec-clip'
      CLUSTER_HOSTNAME: 'node1'
      CLIP_INFERENCE_API: http://multi2vec-clip:8080

  multi2vec-clip:
    image: cr.weaviate.io/semitechnologies/multi2vec-clip:sentence-transformers-clip-ViT-B-32-multilingual-v1
    container_name: clip
    environment:
      ENABLE_CUDA: '0'

  acuity:
    image: codeberg.org/shlks/acuity:latest
    pull_policy: always
    container_name: acuity
    ports:
      - "3000:3000"
    volumes:
      - ./acuity.db:/app/acuity.db
      - ./config.json:/app/config.json
      - ./testdata:/data/testdata:rw
    environment:
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_PORT=:50050
    restart: on-failure

volumes:
  weaviate_data:
