// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_test.go -package=gallery
//

// Package gallery is a generated GoMock package.
package gallery

import (
	db "acuity/pkg/db"
	context "context"
	reflect "reflect"

	models "github.com/weaviate/weaviate/entities/models"
	gomock "go.uber.org/mock/gomock"
)

// MocksService is a mock of sService interface.
type MocksService struct {
	ctrl     *gomock.Controller
	recorder *MocksServiceMockRecorder
	isgomock struct{}
}

// MocksServiceMockRecorder is the mock recorder for MocksService.
type MocksServiceMockRecorder struct {
	mock *MocksService
}

// NewMocksService creates a new mock instance.
func NewMocksService(ctrl *gomock.Controller) *MocksService {
	mock := &MocksService{ctrl: ctrl}
	mock.recorder = &MocksServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksService) EXPECT() *MocksServiceMockRecorder {
	return m.recorder
}

// GetAllGalleries mocks base method.
func (m *MocksService) GetAllGalleries() ([]db.Gallery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllGalleries")
	ret0, _ := ret[0].([]db.Gallery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllGalleries indicates an expected call of GetAllGalleries.
func (mr *MocksServiceMockRecorder) GetAllGalleries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllGalleries", reflect.TypeOf((*MocksService)(nil).GetAllGalleries))
}

// GetGalleryByID mocks base method.
func (m *MocksService) GetGalleryByID(id int) (db.Gallery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGalleryByID", id)
	ret0, _ := ret[0].(db.Gallery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGalleryByID indicates an expected call of GetGalleryByID.
func (mr *MocksServiceMockRecorder) GetGalleryByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGalleryByID", reflect.TypeOf((*MocksService)(nil).GetGalleryByID), id)
}

// GetGalleryByName mocks base method.
func (m *MocksService) GetGalleryByName(name string) (db.Gallery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGalleryByName", name)
	ret0, _ := ret[0].(db.Gallery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGalleryByName indicates an expected call of GetGalleryByName.
func (mr *MocksServiceMockRecorder) GetGalleryByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGalleryByName", reflect.TypeOf((*MocksService)(nil).GetGalleryByName), name)
}

// InitTable mocks base method.
func (m *MocksService) InitTable() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitTable")
	ret0, _ := ret[0].(error)
	return ret0
}

// InitTable indicates an expected call of InitTable.
func (mr *MocksServiceMockRecorder) InitTable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitTable", reflect.TypeOf((*MocksService)(nil).InitTable))
}

// InsertGallery mocks base method.
func (m *MocksService) InsertGallery(path, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertGallery", path, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertGallery indicates an expected call of InsertGallery.
func (mr *MocksServiceMockRecorder) InsertGallery(path, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertGallery", reflect.TypeOf((*MocksService)(nil).InsertGallery), path, name)
}

// RemoveGallery mocks base method.
func (m *MocksService) RemoveGallery(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveGallery", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveGallery indicates an expected call of RemoveGallery.
func (mr *MocksServiceMockRecorder) RemoveGallery(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveGallery", reflect.TypeOf((*MocksService)(nil).RemoveGallery), id)
}

// UpdateGallery mocks base method.
func (m *MocksService) UpdateGallery(id int, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGallery", id, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGallery indicates an expected call of UpdateGallery.
func (mr *MocksServiceMockRecorder) UpdateGallery(id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGallery", reflect.TypeOf((*MocksService)(nil).UpdateGallery), id, name)
}

// MockwService is a mock of wService interface.
type MockwService struct {
	ctrl     *gomock.Controller
	recorder *MockwServiceMockRecorder
	isgomock struct{}
}

// MockwServiceMockRecorder is the mock recorder for MockwService.
type MockwServiceMockRecorder struct {
	mock *MockwService
}

// NewMockwService creates a new mock instance.
func NewMockwService(ctrl *gomock.Controller) *MockwService {
	mock := &MockwService{ctrl: ctrl}
	mock.recorder = &MockwServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockwService) EXPECT() *MockwServiceMockRecorder {
	return m.recorder
}

// ChangeGallery mocks base method.
func (m *MockwService) ChangeGallery(ctx context.Context, newID int, images []db.WImage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeGallery", ctx, newID, images)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeGallery indicates an expected call of ChangeGallery.
func (mr *MockwServiceMockRecorder) ChangeGallery(ctx, newID, images any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeGallery", reflect.TypeOf((*MockwService)(nil).ChangeGallery), ctx, newID, images)
}

// CopyToGallery mocks base method.
func (m *MockwService) CopyToGallery(ctx context.Context, newGalleryID int, images []db.WImage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyToGallery", ctx, newGalleryID, images)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyToGallery indicates an expected call of CopyToGallery.
func (mr *MockwServiceMockRecorder) CopyToGallery(ctx, newGalleryID, images any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyToGallery", reflect.TypeOf((*MockwService)(nil).CopyToGallery), ctx, newGalleryID, images)
}

// FindDublicates mocks base method.
func (m *MockwService) FindDublicates(ctx context.Context, imageID string, galleryID, page, imagesPerPage int, threshold float32) ([]db.WImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDublicates", ctx, imageID, galleryID, page, imagesPerPage, threshold)
	ret0, _ := ret[0].([]db.WImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDublicates indicates an expected call of FindDublicates.
func (mr *MockwServiceMockRecorder) FindDublicates(ctx, imageID, galleryID, page, imagesPerPage, threshold any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDublicates", reflect.TypeOf((*MockwService)(nil).FindDublicates), ctx, imageID, galleryID, page, imagesPerPage, threshold)
}

// GetAll mocks base method.
func (m *MockwService) GetAll(ctx context.Context, galleryID int, sortBy, sortOrder string, page, imagesPerPage int, flagFilter, folderFilter string) ([]db.WImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, galleryID, sortBy, sortOrder, page, imagesPerPage, flagFilter, folderFilter)
	ret0, _ := ret[0].([]db.WImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockwServiceMockRecorder) GetAll(ctx, galleryID, sortBy, sortOrder, page, imagesPerPage, flagFilter, folderFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockwService)(nil).GetAll), ctx, galleryID, sortBy, sortOrder, page, imagesPerPage, flagFilter, folderFilter)
}

// GetGalleryCount mocks base method.
func (m *MockwService) GetGalleryCount(ctx context.Context, galleryID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGalleryCount", ctx, galleryID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGalleryCount indicates an expected call of GetGalleryCount.
func (mr *MockwServiceMockRecorder) GetGalleryCount(ctx, galleryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGalleryCount", reflect.TypeOf((*MockwService)(nil).GetGalleryCount), ctx, galleryID)
}

// GetInfo mocks base method.
func (m *MockwService) GetInfo(ctx context.Context, imageID string) (db.WImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfo", ctx, imageID)
	ret0, _ := ret[0].(db.WImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInfo indicates an expected call of GetInfo.
func (mr *MockwServiceMockRecorder) GetInfo(ctx, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfo", reflect.TypeOf((*MockwService)(nil).GetInfo), ctx, imageID)
}

// GetKnownPaths mocks base method.
func (m *MockwService) GetKnownPaths(ctx context.Context, galleryID int) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnownPaths", ctx, galleryID)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKnownPaths indicates an expected call of GetKnownPaths.
func (mr *MockwServiceMockRecorder) GetKnownPaths(ctx, galleryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnownPaths", reflect.TypeOf((*MockwService)(nil).GetKnownPaths), ctx, galleryID)
}

// GetVectors mocks base method.
func (m *MockwService) GetVectors(ctx context.Context, galleryIDs []int) ([]db.ImageVector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVectors", ctx, galleryIDs)
	ret0, _ := ret[0].([]db.ImageVector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVectors indicates an expected call of GetVectors.
func (mr *MockwServiceMockRecorder) GetVectors(ctx, galleryIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVectors", reflect.TypeOf((*MockwService)(nil).GetVectors), ctx, galleryIDs)
}

// ImportImages mocks base method.
func (m *MockwService) ImportImages(ctx context.Context, filePaths []string, galleryID int, progressCallback func(int)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ImportImages", ctx, filePaths, galleryID, progressCallback)
}

// ImportImages indicates an expected call of ImportImages.
func (mr *MockwServiceMockRecorder) ImportImages(ctx, filePaths, galleryID, progressCallback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportImages", reflect.TypeOf((*MockwService)(nil).ImportImages), ctx, filePaths, galleryID, progressCallback)
}

// RemoveGalleryImages mocks base method.
func (m *MockwService) RemoveGalleryImages(ctx context.Context, galleryID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveGalleryImages", ctx, galleryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveGalleryImages indicates an expected call of RemoveGalleryImages.
func (mr *MockwServiceMockRecorder) RemoveGalleryImages(ctx, galleryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveGalleryImages", reflect.TypeOf((*MockwService)(nil).RemoveGalleryImages), ctx, galleryID)
}

// RemoveImage mocks base method.
func (m *MockwService) RemoveImage(ctx context.Context, image db.WImage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveImage", ctx, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveImage indicates an expected call of RemoveImage.
func (mr *MockwServiceMockRecorder) RemoveImage(ctx, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveImage", reflect.TypeOf((*MockwService)(nil).RemoveImage), ctx, image)
}

// RemoveImages mocks base method.
func (m *MockwService) RemoveImages(ctx context.Context, images []db.WImage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveImages", ctx, images)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveImages indicates an expected call of RemoveImages.
func (mr *MockwServiceMockRecorder) RemoveImages(ctx, images any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveImages", reflect.TypeOf((*MockwService)(nil).RemoveImages), ctx, images)
}

// ResetDatabase mocks base method.
func (m *MockwService) ResetDatabase(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetDatabase", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetDatabase indicates an expected call of ResetDatabase.
func (mr *MockwServiceMockRecorder) ResetDatabase(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetDatabase", reflect.TypeOf((*MockwService)(nil).ResetDatabase), ctx)
}

// SearchImage mocks base method.
func (m *MockwService) SearchImage(ctx context.Context, search string, galleryID int, sortBy, sortOrder string, page, imagesPerPage int, threshold float32, flagFilter string) ([]db.WImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchImage", ctx, search, galleryID, sortBy, sortOrder, page, imagesPerPage, threshold, flagFilter)
	ret0, _ := ret[0].([]db.WImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchImage indicates an expected call of SearchImage.
func (mr *MockwServiceMockRecorder) SearchImage(ctx, search, galleryID, sortBy, sortOrder, page, imagesPerPage, threshold, flagFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchImage", reflect.TypeOf((*MockwService)(nil).SearchImage), ctx, search, galleryID, sortBy, sortOrder, page, imagesPerPage, threshold, flagFilter)
}

// SearchImage64 mocks base method.
func (m *MockwService) SearchImage64(ctx context.Context, image string, galleryID int, sortBy, sortOrder string, page, imagesPerPage int, threshold float32, flagFilter string) ([]db.WImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchImage64", ctx, image, galleryID, sortBy, sortOrder, page, imagesPerPage, threshold, flagFilter)
	ret0, _ := ret[0].([]db.WImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchImage64 indicates an expected call of SearchImage64.
func (mr *MockwServiceMockRecorder) SearchImage64(ctx, image, galleryID, sortBy, sortOrder, page, imagesPerPage, threshold, flagFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchImage64", reflect.TypeOf((*MockwService)(nil).SearchImage64), ctx, image, galleryID, sortBy, sortOrder, page, imagesPerPage, threshold, flagFilter)
}

// SetFlag mocks base method.
func (m *MockwService) SetFlag(ctx context.Context, imageID string, flag int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFlag", ctx, imageID, flag)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFlag indicates an expected call of SetFlag.
func (mr *MockwServiceMockRecorder) SetFlag(ctx, imageID, flag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFlag", reflect.TypeOf((*MockwService)(nil).SetFlag), ctx, imageID, flag)
}

// SetRating mocks base method.
func (m *MockwService) SetRating(ctx context.Context, imageID string, rating int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRating", ctx, imageID, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRating indicates an expected call of SetRating.
func (mr *MockwServiceMockRecorder) SetRating(ctx, imageID, rating any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRating", reflect.TypeOf((*MockwService)(nil).SetRating), ctx, imageID, rating)
}

// WriteBatchDB mocks base method.
func (m *MockwService) WriteBatchDB(ctx context.Context, batch []*models.Object) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteBatchDB", ctx, batch)
	ret0, _ := ret[0].(int)
	return ret0
}

// WriteBatchDB indicates an expected call of WriteBatchDB.
func (mr *MockwServiceMockRecorder) WriteBatchDB(ctx, batch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteBatchDB", reflect.TypeOf((*MockwService)(nil).WriteBatchDB), ctx, batch)
}
